package com.example.pickme.models;

import com.google.firebase.Timestamp;

/**
 * Represents a facility created by an organizer
 * @author sophiecabungcal
 * @version 1.0
 */
public class Facility {

    /* Facility Attributes */
    // the unique facility id; auto-generated by Firebase [non-nullable]
    private String facilityId;
    // the owner id referencing userId from users collection of facility owner [non-nullable]
    private String ownerId;
    // the name of the facility [non-nullable]
    private String facilityName;
    // the date/time the facility was created [non-nullable]
    private final Timestamp createdAt;
    // the date/time the facility was last updated [non-nullable]
    private Timestamp updatedAt;

    public Facility() {
        this.createdAt = Timestamp.now();
    }

    public Facility(String ownerId, String facilityName) {
        this.ownerId = ownerId;
        this.facilityName = facilityName;
        this.createdAt = Timestamp.now();
        this.updatedAt = Timestamp.now();
    }

    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId;
    }

    public String getFacilityId() {
        return facilityId;
    }

    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
        this.updatedAt = Timestamp.now();
    }

    public String getOwnerId() {
        return ownerId;
    }

    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName;
        this.updatedAt = Timestamp.now();
    }

    public String getFacilityName() {
        return facilityName;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }
}
