package com.example.pickme.models;

import com.example.pickme.models.Enums.QrType;
import com.google.firebase.Timestamp;

/**
 * Represents a QR code requested/created by the user
 * @author sophiecabungcal
 * @version 1.0
 */
public class QR {

    /* QR Attributes */
    // the unique qr id; auto-generated by Firebase [non-nullable]
    private String qrId;
    // the hash data of the qr [non-nullable]
    private String qrData;
    // the type of qr (event poster, waiting list) [non-nullable]
    private QrType type;
    // references the associated entity id that the qr is for (event, waiting list) [non-nullable]
    private String qrAssociation;
    // the user id of the uploader [non-nullable]
    private String uploaderId;
    // the date/time the qr was created [non-nullable]
    private final Timestamp createdAt;
    // the date/time the qr was last updated [non-nullable]
    private Timestamp updatedAt;

    public QR() {
        this.createdAt = Timestamp.now();
    }

    public QR(String qrData, QrType type, String qrAssociation, String uploaderId) {
        this.qrData = qrData;
        this.type = type;
        this.qrAssociation = qrAssociation;
        this.uploaderId = uploaderId;
        this.createdAt = Timestamp.now();
        this.updatedAt = Timestamp.now();
    }

    public void setQrId(String qrId) {
        this.qrId = qrId;
    }

    public String getQrId() {
        return qrId;
    }

    public void setQrData(String qrData) {
        this.qrData = qrData;
        this.updatedAt = Timestamp.now();
    }

    public String getQrData() {
        return qrData;
    }

    public void setType(QrType type) {
        this.type = type;
        this.updatedAt = Timestamp.now();
    }

    public QrType getType() {
        return type;
    }

    public void setQrAssociation(String qrAssociation) {
        this.qrAssociation = qrAssociation;
        this.updatedAt = Timestamp.now();
    }

    public String getQrAssociation() {
        return qrAssociation;
    }

    public void setUploaderId(String uploaderId) {
        this.uploaderId = uploaderId;
        this.updatedAt = Timestamp.now();
    }

    public String getUploaderId() {
        return uploaderId;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }
}
