package com.example.pickme.models;

/**
 * Represents a QR code requested or created by the user.
 * This class stores the unique identifier of the QR code and its associated entity.
 * The QR code is auto-generated by Firebase and is linked to an entity such as an event or a waiting list.
 *
 *
 * @version 1.1
 */
public class QR {

    /* QR Attributes */

    /** The unique QR code identifier, auto-generated by Firebase. */
    private String qrId;

    /** References the associated entity ID for the QR code (e.g., event, waiting list). */
    private String qrAssociation;

    /**
     * Default constructor.
     * Initializes a new instance of the QR class without setting any attributes.
     */
    public QR() {
        // Default constructor
    }

    /**
     * Initializes a new instance of the QR class with the specified association.
     *
     * @param qrAssociation The associated entity ID for this QR code.
     */
    public QR(String qrAssociation) {
        this.qrAssociation = qrAssociation;
    }

    /**
     * Sets the unique identifier for the QR code.
     *
     * @param qrId The unique QR code ID generated by Firebase.
     */
    public void setQrId(String qrId) {
        this.qrId = qrId;
    }

    /**
     * Retrieves the unique identifier for the QR code.
     *
     * @return The unique QR code ID.
     */
    public String getQrId() {
        return qrId;
    }

    /**
     * Retrieves the associated entity ID for this QR code.
     *
     * @return The associated entity ID.
     */
    public String getQrAssociation() {
        return qrAssociation;
    }
}
