package com.example.pickme.models;

import com.google.firebase.Timestamp;

/**
 * Represents the waiting list for an event
 * @author sophiecabungcal
 * @version 1.0
 */
public class WaitingList {

    /* Waiting List Attributes */
    // the unique waiting list id; auto-generated by Firebase [non-nullable]
    private String waitingListId;
    // the event id referencing eventId from events collection [non-nullable]
    private String eventId;
    // the maximum number of entrants allowed on the waiting list [nullable]
    private Integer maxEntrants;
    // the date/time the waiting list was created [non-nullable]
    private final Timestamp createdAt;
    // the date/time the waiting list was last updated [non-nullable]
    private Timestamp updatedAt;

    public WaitingList() {
        this.createdAt = Timestamp.now();
    }

    public WaitingList(String eventId, Integer maxEntrants) {
        this.eventId = eventId;
        this.maxEntrants = maxEntrants;
        this.createdAt = Timestamp.now();
        this.updatedAt = Timestamp.now();
    }

    public void setWaitingListId(String waitingListId) {
        this.waitingListId = waitingListId;
    }

    public String getWaitingListId() {
        return waitingListId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
        this.updatedAt = Timestamp.now();
    }

    public String getEventId() {
        return eventId;
    }

    public void setMaxEntrants(Integer maxEntrants) {
        this.maxEntrants = maxEntrants;
        this.updatedAt = Timestamp.now();
    }

    public Integer getMaxEntrants() {
        return maxEntrants;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }
}
