package com.example.pickme.models;

import com.example.pickme.models.Enums.Status;
import com.google.firebase.Timestamp;
import com.google.firebase.firestore.GeoPoint;

/**
 * Represents the waiting list entrants for an event's waiting list
 * @author sophiecabungcal
 * @version 1.0
 */
public class WaitingListEntrant {

    /* Waiting List Entrant Attributes */
    // the unique waiting list entrant id; auto-generated by Firebase [non-nullable]
    private String waitListEntrantId;
    // the entrant id referencing userId from users collection [non-nullable]
    private String entrantId;
    // the location of the entrant [nullable]
    private GeoPoint geoLocation;
    // the status of the entrant on the waiting list [non-nullable]
    private Status status;
    // boolean value representing whether the entrant has been notified [non-nullable]
    private boolean notified;
    // the date/time the entrant joined the waiting list [non-nullable]
    private final Timestamp createdAt;
    // the date/time the entrant was last updated [non-nullable]
    private Timestamp updatedAt;

    public WaitingListEntrant() {
        this.createdAt = Timestamp.now();
    }

    public WaitingListEntrant(String entrantId, GeoPoint geoLocation, Status status) {
        this.entrantId = entrantId;
        this.geoLocation = geoLocation;
        this.status = status;
        this.createdAt = Timestamp.now();
        this.updatedAt = Timestamp.now();
    }

    public void setWaitListEntrantId(String waitListEntrantId) {
        this.waitListEntrantId = waitListEntrantId;
    }

    public String getWaitListEntrantId() {
        return waitListEntrantId;
    }

    public void setEntrantId(String entrantId) {
        this.entrantId = entrantId;
        this.updatedAt = Timestamp.now();
    }

    public String getEntrantId() {
        return entrantId;
    }

    public void setGeoLocation(GeoPoint geoLocation) {
        this.geoLocation = geoLocation;
        this.updatedAt = Timestamp.now();
    }

    public GeoPoint getGeoLocation() {
        return geoLocation;
    }

    public void setStatus(Status status) {
        this.status = status;
        this.updatedAt = Timestamp.now();
    }

    public Status getStatus() {
        return status;
    }

    public void setNotified(boolean notified) {
        this.notified = notified;
        this.updatedAt = Timestamp.now();
    }

    public boolean isNotified() {
        return notified;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }
}
